---
title: drakortivi
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
email: 
description: Streaming dan download drama korea di sini. GRATIS!!!
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  name: Mas Bagus
  avatar: "/assets/images/bio-photo.jpg"
  bio: Sepenuh hati mengelola blog ini.
  links:
  - label: Website
    icon: fas fa-fw fa-link
    url: https://drakortivi.github.io
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: 
  - label: Telegram
    icon: fab fa-fw fa-telegram
    url: https://t.me/drakorviagdrive
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: 
footer:
  links:
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: 
  - label: Telegram
    icon: fab fa-fw fa-telegram
    url: https://t.me/drakorviagdrive
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: 
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
head_scripts:
  - https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css
after_footer_scripts:
  - https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js
